{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-datetime",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-datetime-metadata-0.6.0.jar",
          "url": "kotlinx-datetime-0.6.0.jar",
          "size": 61387,
          "sha512": "a62818dc7bfb11910caa461cfd70da0e2c2bbd2f476ad36df90728dffbc6767c915609ca311fa69b42b31058f6ef008a75667bc094d0268e0011ca6af431b002",
          "sha256": "c109d00feffc420018433bdc2f6f8de6c4eedadaf2cce80eeb550cddb150251b",
          "sha1": "7f00229f2daa3f6e772e42bcefd3cd13fb1e34cd",
          "md5": "9109eba40cec0f27dde1dd952548a22c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlinx-datetime-kotlin-0.6.0-sources.jar",
          "url": "kotlinx-datetime-0.6.0-sources.jar",
          "size": 165375,
          "sha512": "546c85b00a08801b96f4e90f27c1c9e7cfef23e89cc4bf7b62c9366d8863b84512a56a243d99ab174f3614a10017fd9a364a1d76f841b780fde9ca55e782bfc4",
          "sha256": "177290601bb1d3e5d6039a453884ba604d96359b739478b082c6cc680bd7fa1c",
          "sha1": "6ea72ae3c55b5f7ec5bfb005ccc37c81d2737637",
          "md5": "c25b0979540275ca0674ad7544ca3c8b"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-androidnativearm32/0.6.0/kotlinx-datetime-androidnativearm32-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-androidnativearm32",
        "version": "0.6.0"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-androidnativearm32/0.6.0/kotlinx-datetime-androidnativearm32-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-androidnativearm32",
        "version": "0.6.0"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-androidnativearm64/0.6.0/kotlinx-datetime-androidnativearm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-androidnativearm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-androidnativearm64/0.6.0/kotlinx-datetime-androidnativearm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-androidnativearm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-androidnativex64/0.6.0/kotlinx-datetime-androidnativex64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-androidnativex64",
        "version": "0.6.0"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-androidnativex64/0.6.0/kotlinx-datetime-androidnativex64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-androidnativex64",
        "version": "0.6.0"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-androidnativex86/0.6.0/kotlinx-datetime-androidnativex86-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-androidnativex86",
        "version": "0.6.0"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-androidnativex86/0.6.0/kotlinx-datetime-androidnativex86-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-androidnativex86",
        "version": "0.6.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-iosarm64/0.6.0/kotlinx-datetime-iosarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-iosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-iosarm64/0.6.0/kotlinx-datetime-iosarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-iosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-iosarm64/0.6.0/kotlinx-datetime-iosarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-iosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-iossimulatorarm64/0.6.0/kotlinx-datetime-iossimulatorarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-iossimulatorarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-iossimulatorarm64/0.6.0/kotlinx-datetime-iossimulatorarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-iossimulatorarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-iossimulatorarm64/0.6.0/kotlinx-datetime-iossimulatorarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-iossimulatorarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-iosx64/0.6.0/kotlinx-datetime-iosx64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-iosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-iosx64/0.6.0/kotlinx-datetime-iosx64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-iosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-iosx64/0.6.0/kotlinx-datetime-iosx64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-iosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-js/0.6.0/kotlinx-datetime-js-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-js",
        "version": "0.6.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-js/0.6.0/kotlinx-datetime-js-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-js",
        "version": "0.6.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-js/0.6.0/kotlinx-datetime-js-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-js",
        "version": "0.6.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-jvm/0.6.0/kotlinx-datetime-jvm-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-jvm",
        "version": "0.6.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-jvm/0.6.0/kotlinx-datetime-jvm-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-jvm",
        "version": "0.6.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-jvm/0.6.0/kotlinx-datetime-jvm-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-jvm",
        "version": "0.6.0"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-linuxarm32hfp/0.6.0/kotlinx-datetime-linuxarm32hfp-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-linuxarm32hfp",
        "version": "0.6.0"
      }
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-linuxarm32hfp/0.6.0/kotlinx-datetime-linuxarm32hfp-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-linuxarm32hfp",
        "version": "0.6.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-linuxarm64/0.6.0/kotlinx-datetime-linuxarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-linuxarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-linuxarm64/0.6.0/kotlinx-datetime-linuxarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-linuxarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-linuxx64/0.6.0/kotlinx-datetime-linuxx64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-linuxx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-linuxx64/0.6.0/kotlinx-datetime-linuxx64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-linuxx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-macosarm64/0.6.0/kotlinx-datetime-macosarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-macosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-macosarm64/0.6.0/kotlinx-datetime-macosarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-macosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-macosarm64/0.6.0/kotlinx-datetime-macosarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-macosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-macosx64/0.6.0/kotlinx-datetime-macosx64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-macosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-macosx64/0.6.0/kotlinx-datetime-macosx64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-macosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-macosx64/0.6.0/kotlinx-datetime-macosx64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-macosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-mingwx64/0.6.0/kotlinx-datetime-mingwx64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-mingwx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-mingwx64/0.6.0/kotlinx-datetime-mingwx64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-mingwx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-tvosarm64/0.6.0/kotlinx-datetime-tvosarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-tvosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-tvosarm64/0.6.0/kotlinx-datetime-tvosarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-tvosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-tvosarm64/0.6.0/kotlinx-datetime-tvosarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-tvosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-tvossimulatorarm64/0.6.0/kotlinx-datetime-tvossimulatorarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-tvossimulatorarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-tvossimulatorarm64/0.6.0/kotlinx-datetime-tvossimulatorarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-tvossimulatorarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-tvossimulatorarm64/0.6.0/kotlinx-datetime-tvossimulatorarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-tvossimulatorarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-tvosx64/0.6.0/kotlinx-datetime-tvosx64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-tvosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-tvosx64/0.6.0/kotlinx-datetime-tvosx64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-tvosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-tvosx64/0.6.0/kotlinx-datetime-tvosx64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-tvosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-wasm-js/0.6.0/kotlinx-datetime-wasm-js-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-wasm-js",
        "version": "0.6.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-wasm-js/0.6.0/kotlinx-datetime-wasm-js-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-wasm-js",
        "version": "0.6.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-wasm-js/0.6.0/kotlinx-datetime-wasm-js-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-wasm-js",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-watchosarm32/0.6.0/kotlinx-datetime-watchosarm32-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-watchosarm32",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-watchosarm32/0.6.0/kotlinx-datetime-watchosarm32-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-watchosarm32",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-watchosarm32/0.6.0/kotlinx-datetime-watchosarm32-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-watchosarm32",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-watchosarm64/0.6.0/kotlinx-datetime-watchosarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-watchosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-watchosarm64/0.6.0/kotlinx-datetime-watchosarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-watchosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-watchosarm64/0.6.0/kotlinx-datetime-watchosarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-watchosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-watchosdevicearm64/0.6.0/kotlinx-datetime-watchosdevicearm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-watchosdevicearm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-watchosdevicearm64/0.6.0/kotlinx-datetime-watchosdevicearm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-watchosdevicearm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-watchosdevicearm64/0.6.0/kotlinx-datetime-watchosdevicearm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-watchosdevicearm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-watchossimulatorarm64/0.6.0/kotlinx-datetime-watchossimulatorarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-watchossimulatorarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-watchossimulatorarm64/0.6.0/kotlinx-datetime-watchossimulatorarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-watchossimulatorarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-watchossimulatorarm64/0.6.0/kotlinx-datetime-watchossimulatorarm64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-watchossimulatorarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-watchosx64/0.6.0/kotlinx-datetime-watchosx64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-watchosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-watchosx64/0.6.0/kotlinx-datetime-watchosx64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-watchosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-datetime-watchosx64/0.6.0/kotlinx-datetime-watchosx64-0.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-datetime-watchosx64",
        "version": "0.6.0"
      }
    }
  ]
}
