{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.6.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.6.1.jar",
          "url": "builder-8.6.1.jar",
          "size": 14458519,
          "sha512": "f70c296b8da4308db9bcd96b9c53cfefe53082b2789e2a137a78dbc1887a857df0ca45df4c49cdad545303e1c622613264b2210703ecf448c4f83989c06b4b20",
          "sha256": "bc4ee949f4ee95381c835487ebb6b1964889d6104b032397967d88b4f206e48d",
          "sha1": "3ede92b2242a7a5b214479bd81c75c6c894308e8",
          "md5": "78d4db569ec1f44ec7fbba94c64bfa2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.6.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.6.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.6.1"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.6.1"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.6.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.6.1"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.6.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.6.1.jar",
          "url": "builder-8.6.1.jar",
          "size": 14458519,
          "sha512": "f70c296b8da4308db9bcd96b9c53cfefe53082b2789e2a137a78dbc1887a857df0ca45df4c49cdad545303e1c622613264b2210703ecf448c4f83989c06b4b20",
          "sha256": "bc4ee949f4ee95381c835487ebb6b1964889d6104b032397967d88b4f206e48d",
          "sha1": "3ede92b2242a7a5b214479bd81c75c6c894308e8",
          "md5": "78d4db569ec1f44ec7fbba94c64bfa2e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.6.1-javadoc.jar",
          "url": "builder-8.6.1-javadoc.jar",
          "size": 397693,
          "sha512": "999175c38393450763beb2c326b6aceb753ea5b89ffeda762b1965c1430db1287acf87231018d71d554f5d629123e3dd7b5adcb342589fd6a9109e6d919ec6a1",
          "sha256": "62d498a307ecc34333a7bd8a30f072a94efbe7e6c8542cb6f699c064c4ef53e1",
          "sha1": "5cdea0b7dff6de9ca889bed2715908dec0a9e70d",
          "md5": "877f7c262fd643e346721458613f87a2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.6.1-sources.jar",
          "url": "builder-8.6.1-sources.jar",
          "size": 281038,
          "sha512": "862acc4f0eec405e0037d70622f257a22a2ce6b7acccd55acd089cd1bb64cef13f15cc0239d8a6299b48e840cfc04bac767954b61a89654935a5704459b3f7ca",
          "sha256": "1a283cdc4e05dd528358b193f076d945ae3b31f1f79ff367baa03c8f56d3819a",
          "sha1": "ac58164708877312e43d3eca4431f48f4028459a",
          "md5": "f7e8ad3cdf26a3eb4b3d6a712fc2a25c"
        }
      ]
    }
  ]
}
