{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-metadata-1.5.0-all.jar",
          "url": "kotlinx-serialization-core-1.5.0-all.jar",
          "size": 36516,
          "sha512": "fa09abd6d1cd5fb069294f029d70d7241239f4870eaddc6741304ae12624e9531d433cd17a3c3a5d39c779d1c90230768271d428cc9d5329e5df0fe153405cf9",
          "sha256": "ea58183fe54fd39f1857579c2c36e393d3d9a3a98f244f684f0b1e0355ff1520",
          "sha1": "3ff03d5b56fe8f5f2d4d52e6d5148026757c2815",
          "md5": "ba3b351367772dd33c8c6817d17d35de"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-1.5.0.jar",
          "url": "kotlinx-serialization-core-1.5.0.jar",
          "size": 98229,
          "sha512": "b8791167b0d9b71ec51ca56b4676d033c1ec83d328e7a686a6b075a0be48cc303f3ca638f666ae5d5d71f038ad4ce0da5fa7b61816c951a6813f4a8474d2cd83",
          "sha256": "47bacc3c340c4eb36f88f6648b8417f4ced8f67c91b01ea1ed68d76789cd4311",
          "sha1": "c334a192a2a4ef8ae60340111d4d51edbb5b8a00",
          "md5": "15bc59394ce860f88ff75f9ee9bce5eb"
        }
      ]
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosarm32/1.5.0/kotlinx-serialization-core-iosarm32-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosarm32",
        "version": "1.5.0"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosarm32/1.5.0/kotlinx-serialization-core-iosarm32-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosarm32",
        "version": "1.5.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosarm64/1.5.0/kotlinx-serialization-core-iosarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosarm64/1.5.0/kotlinx-serialization-core-iosarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iossimulatorarm64/1.5.0/kotlinx-serialization-core-iossimulatorarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iossimulatorarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iossimulatorarm64/1.5.0/kotlinx-serialization-core-iossimulatorarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iossimulatorarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosx64/1.5.0/kotlinx-serialization-core-iosx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosx64/1.5.0/kotlinx-serialization-core-iosx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-js/1.5.0/kotlinx-serialization-core-js-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-js",
        "version": "1.5.0"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-js/1.5.0/kotlinx-serialization-core-js-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-js",
        "version": "1.5.0"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-js/1.5.0/kotlinx-serialization-core-js-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-js",
        "version": "1.5.0"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-js/1.5.0/kotlinx-serialization-core-js-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-js",
        "version": "1.5.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-jvm/1.5.0/kotlinx-serialization-core-jvm-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-jvm",
        "version": "1.5.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-jvm/1.5.0/kotlinx-serialization-core-jvm-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-jvm",
        "version": "1.5.0"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-linuxarm32hfp/1.5.0/kotlinx-serialization-core-linuxarm32hfp-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-linuxarm32hfp",
        "version": "1.5.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-linuxarm64/1.5.0/kotlinx-serialization-core-linuxarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-linuxarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-linuxx64/1.5.0/kotlinx-serialization-core-linuxx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-linuxx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-macosarm64/1.5.0/kotlinx-serialization-core-macosarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-macosarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-macosarm64/1.5.0/kotlinx-serialization-core-macosarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-macosarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-macosx64/1.5.0/kotlinx-serialization-core-macosx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-macosx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-macosx64/1.5.0/kotlinx-serialization-core-macosx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-macosx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-mingwx64/1.5.0/kotlinx-serialization-core-mingwx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-mingwx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "mingwX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-mingwx86/1.5.0/kotlinx-serialization-core-mingwx86-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-mingwx86",
        "version": "1.5.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvosarm64/1.5.0/kotlinx-serialization-core-tvosarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvosarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvosarm64/1.5.0/kotlinx-serialization-core-tvosarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvosarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvossimulatorarm64/1.5.0/kotlinx-serialization-core-tvossimulatorarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvossimulatorarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvossimulatorarm64/1.5.0/kotlinx-serialization-core-tvossimulatorarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvossimulatorarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvosx64/1.5.0/kotlinx-serialization-core-tvosx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvosx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvosx64/1.5.0/kotlinx-serialization-core-tvosx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvosx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosarm32/1.5.0/kotlinx-serialization-core-watchosarm32-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosarm32",
        "version": "1.5.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosarm32/1.5.0/kotlinx-serialization-core-watchosarm32-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosarm32",
        "version": "1.5.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosarm64/1.5.0/kotlinx-serialization-core-watchosarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosarm64/1.5.0/kotlinx-serialization-core-watchosarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchossimulatorarm64/1.5.0/kotlinx-serialization-core-watchossimulatorarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchossimulatorarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchossimulatorarm64/1.5.0/kotlinx-serialization-core-watchossimulatorarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchossimulatorarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosx64/1.5.0/kotlinx-serialization-core-watchosx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosx64/1.5.0/kotlinx-serialization-core-watchosx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosx86/1.5.0/kotlinx-serialization-core-watchosx86-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosx86",
        "version": "1.5.0"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosx86/1.5.0/kotlinx-serialization-core-watchosx86-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosx86",
        "version": "1.5.0"
      }
    }
  ]
}
