{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.7.3/kotlinx-serialization-json-1.7.3.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.7.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.7.3.jar",
          "url": "kotlinx-serialization-json-jvm-1.7.3.jar",
          "size": 270553,
          "sha512": "fd5df73cca3d7e00cbe8e4b95f901509ae5a788ccc57709932995e16c31e8661c4e2b1584a91481a327a5332eefb01c85c28b7c44e1e34a18888026c8057c0a0",
          "sha256": "b1e9138499ed8d20375edda3f2b1c95f3103a258eff6af9edc5ea07100f2b29c",
          "sha1": "6701e8c68d9e82387ce72ee96e8ddf058208d58f",
          "md5": "b1f7c0e3bc8e8a5901b83f0f602cebd0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.7.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.7.3.jar",
          "url": "kotlinx-serialization-json-jvm-1.7.3.jar",
          "size": 270553,
          "sha512": "fd5df73cca3d7e00cbe8e4b95f901509ae5a788ccc57709932995e16c31e8661c4e2b1584a91481a327a5332eefb01c85c28b7c44e1e34a18888026c8057c0a0",
          "sha256": "b1e9138499ed8d20375edda3f2b1c95f3103a258eff6af9edc5ea07100f2b29c",
          "sha1": "6701e8c68d9e82387ce72ee96e8ddf058208d58f",
          "md5": "b1f7c0e3bc8e8a5901b83f0f602cebd0"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.7.3-sources.jar",
          "url": "kotlinx-serialization-json-jvm-1.7.3-sources.jar",
          "size": 89115,
          "sha512": "39e80f81d3b678a887a81477126db4498fc10b5308663ceb331839b44682b3bc0f8bf86bf53e0ba8c7309c4828e0782350d8274fe08a3d8be14c23fa1293ddf7",
          "sha256": "fddb3c7e3c92692769285476308dd7a39009aed1e8ae80112169d72d75a275ab",
          "sha1": "50dea2620c51cdcffac780fe0bf0148b209e7477",
          "md5": "ef315db10bd5a5c08d0042bde01c749e"
        }
      ]
    }
  ]
}
