{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-test",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-test-metadata-1.9.0.jar",
          "url": "kotlinx-coroutines-test-1.9.0.jar",
          "size": 14872,
          "sha512": "69fbae7ed81dbaaa51a388814dde8cff449d2081cf6885784596bb98af09e7f26e5104b249d1532d0aded3ec04a4e5e5a29ab104beb2ce7f1d256096dc994d5e",
          "sha256": "b9f0603718765fe9f93b4a139198ada254f11c7bf18e48c99629a3a73ce281d1",
          "sha1": "5b34f17d0ec2d3393154debef5091ef99f44b80c",
          "md5": "eb18bdfee7bc7b723c2b6ffeb096765f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-test-kotlin-1.9.0-sources.jar",
          "url": "kotlinx-coroutines-test-1.9.0-sources.jar",
          "size": 25653,
          "sha512": "37ac34d8e5bc50de6a368c33aa28cabc1ffa4c1cde99a5dc61fa0d95eadf8ab4bd2568df1782705b859d46424ff7c0217f5e5061e29a5bdfb28273d00d5ee79c",
          "sha256": "ced85445c16d1b7ec16a27c58e03f214aface9b340cb2a43e3f1f925c2d5f3c0",
          "sha1": "4008674842816efaaf87acc5a524dffd12974306",
          "md5": "b492f42e0d555de30e07eebff39f00a7"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-androidnativearm32/1.9.0/kotlinx-coroutines-test-androidnativearm32-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-androidnativearm32",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-androidnativearm32/1.9.0/kotlinx-coroutines-test-androidnativearm32-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-androidnativearm32",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-androidnativearm64/1.9.0/kotlinx-coroutines-test-androidnativearm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-androidnativearm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-androidnativearm64/1.9.0/kotlinx-coroutines-test-androidnativearm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-androidnativearm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-androidnativex64/1.9.0/kotlinx-coroutines-test-androidnativex64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-androidnativex64",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-androidnativex64/1.9.0/kotlinx-coroutines-test-androidnativex64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-androidnativex64",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-androidnativex86/1.9.0/kotlinx-coroutines-test-androidnativex86-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-androidnativex86",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-androidnativex86/1.9.0/kotlinx-coroutines-test-androidnativex86-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-androidnativex86",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iosarm64/1.9.0/kotlinx-coroutines-test-iosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iosarm64/1.9.0/kotlinx-coroutines-test-iosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iosarm64/1.9.0/kotlinx-coroutines-test-iosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iossimulatorarm64/1.9.0/kotlinx-coroutines-test-iossimulatorarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iossimulatorarm64/1.9.0/kotlinx-coroutines-test-iossimulatorarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iossimulatorarm64/1.9.0/kotlinx-coroutines-test-iossimulatorarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iosx64/1.9.0/kotlinx-coroutines-test-iosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iosx64/1.9.0/kotlinx-coroutines-test-iosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iosx64/1.9.0/kotlinx-coroutines-test-iosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-js/1.9.0/kotlinx-coroutines-test-js-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-js",
        "version": "1.9.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-js/1.9.0/kotlinx-coroutines-test-js-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-js",
        "version": "1.9.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-js/1.9.0/kotlinx-coroutines-test-js-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-js",
        "version": "1.9.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-jvm/1.9.0/kotlinx-coroutines-test-jvm-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-jvm",
        "version": "1.9.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-jvm/1.9.0/kotlinx-coroutines-test-jvm-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-jvm",
        "version": "1.9.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-jvm/1.9.0/kotlinx-coroutines-test-jvm-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-jvm",
        "version": "1.9.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-linuxarm64/1.9.0/kotlinx-coroutines-test-linuxarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-linuxarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-linuxarm64/1.9.0/kotlinx-coroutines-test-linuxarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-linuxarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-linuxx64/1.9.0/kotlinx-coroutines-test-linuxx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-linuxx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-linuxx64/1.9.0/kotlinx-coroutines-test-linuxx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-linuxx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-macosarm64/1.9.0/kotlinx-coroutines-test-macosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-macosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-macosarm64/1.9.0/kotlinx-coroutines-test-macosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-macosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-macosarm64/1.9.0/kotlinx-coroutines-test-macosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-macosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-macosx64/1.9.0/kotlinx-coroutines-test-macosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-macosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-macosx64/1.9.0/kotlinx-coroutines-test-macosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-macosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-macosx64/1.9.0/kotlinx-coroutines-test-macosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-macosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-mingwx64/1.9.0/kotlinx-coroutines-test-mingwx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-mingwx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-mingwx64/1.9.0/kotlinx-coroutines-test-mingwx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-mingwx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvosarm64/1.9.0/kotlinx-coroutines-test-tvosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvosarm64/1.9.0/kotlinx-coroutines-test-tvosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvosarm64/1.9.0/kotlinx-coroutines-test-tvosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvossimulatorarm64/1.9.0/kotlinx-coroutines-test-tvossimulatorarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvossimulatorarm64/1.9.0/kotlinx-coroutines-test-tvossimulatorarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvossimulatorarm64/1.9.0/kotlinx-coroutines-test-tvossimulatorarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvosx64/1.9.0/kotlinx-coroutines-test-tvosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvosx64/1.9.0/kotlinx-coroutines-test-tvosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvosx64/1.9.0/kotlinx-coroutines-test-tvosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-wasm-js/1.9.0/kotlinx-coroutines-test-wasm-js-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-wasm-js",
        "version": "1.9.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-wasm-js/1.9.0/kotlinx-coroutines-test-wasm-js-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-wasm-js",
        "version": "1.9.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-wasm-js/1.9.0/kotlinx-coroutines-test-wasm-js-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-wasm-js",
        "version": "1.9.0"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-wasm-wasi/1.9.0/kotlinx-coroutines-test-wasm-wasi-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-wasm-wasi",
        "version": "1.9.0"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-wasm-wasi/1.9.0/kotlinx-coroutines-test-wasm-wasi-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-wasm-wasi",
        "version": "1.9.0"
      }
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-wasm-wasi/1.9.0/kotlinx-coroutines-test-wasm-wasi-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-wasm-wasi",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosarm32/1.9.0/kotlinx-coroutines-test-watchosarm32-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosarm32",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosarm32/1.9.0/kotlinx-coroutines-test-watchosarm32-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosarm32",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosarm32/1.9.0/kotlinx-coroutines-test-watchosarm32-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosarm32",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosarm64/1.9.0/kotlinx-coroutines-test-watchosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosarm64/1.9.0/kotlinx-coroutines-test-watchosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosarm64/1.9.0/kotlinx-coroutines-test-watchosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosdevicearm64/1.9.0/kotlinx-coroutines-test-watchosdevicearm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosdevicearm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosdevicearm64/1.9.0/kotlinx-coroutines-test-watchosdevicearm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosdevicearm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosdevicearm64/1.9.0/kotlinx-coroutines-test-watchosdevicearm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosdevicearm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchossimulatorarm64/1.9.0/kotlinx-coroutines-test-watchossimulatorarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchossimulatorarm64/1.9.0/kotlinx-coroutines-test-watchossimulatorarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchossimulatorarm64/1.9.0/kotlinx-coroutines-test-watchossimulatorarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosx64/1.9.0/kotlinx-coroutines-test-watchosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosx64/1.9.0/kotlinx-coroutines-test-watchosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosx64/1.9.0/kotlinx-coroutines-test-watchosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosx64",
        "version": "1.9.0"
      }
    }
  ]
}
