{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-settings-api",
    "version": "8.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.6.1.jar",
          "url": "gradle-settings-api-8.6.1.jar",
          "size": 9836,
          "sha512": "d86c65a3f208e66888eac2fa5762a6f111d17fc880172f4bc4d53d38a019dfb7dfe57b0f0c240df71a77b1b470c767eff5859bdf15592ffd804d3194e931ec2e",
          "sha256": "7ca7dbd0be9120478990e25fb83cf083a3fc79bca9644e247cc5546358ce2982",
          "sha1": "3dcc8067d84767814c021dc5487ee6f09e1b7727",
          "md5": "ad08fadd463f9bc6f18fb4f8e7cf84f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-settings-api-8.6.1.jar",
          "url": "gradle-settings-api-8.6.1.jar",
          "size": 9836,
          "sha512": "d86c65a3f208e66888eac2fa5762a6f111d17fc880172f4bc4d53d38a019dfb7dfe57b0f0c240df71a77b1b470c767eff5859bdf15592ffd804d3194e931ec2e",
          "sha256": "7ca7dbd0be9120478990e25fb83cf083a3fc79bca9644e247cc5546358ce2982",
          "sha1": "3dcc8067d84767814c021dc5487ee6f09e1b7727",
          "md5": "ad08fadd463f9bc6f18fb4f8e7cf84f6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.6.1-javadoc.jar",
          "url": "gradle-settings-api-8.6.1-javadoc.jar",
          "size": 261,
          "sha512": "2e82bd1adaa5b92f95b1ac4e9bdac887955218ea1f64b21123dd90a4f924d4337741596df1f6e6b8b5feb53eec7f2bbbfa502471ca8c8eb9d10d8dedf038c8b2",
          "sha256": "04ce5aae949d0424445066209214d1afffae043bc4bbfbcb3861b52a9ec7bdc5",
          "sha1": "46407916ef82d7c73488e00c74b1e4bbb56a4b32",
          "md5": "5c4fb217085e53838d7a87a10bb22e5b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.6.1-sources.jar",
          "url": "gradle-settings-api-8.6.1-sources.jar",
          "size": 9407,
          "sha512": "0a96a06e4c240344cc4b753a69cee89acb590bd8d6d4ed362158c5d175e040c039fc6b338901ab0df4dcfeef6b0ad052a62f8c7106326d333723ed4772d1c550",
          "sha256": "577c521d1bc62d0bbb80cf379460108136492357b7d65073167f9e2e785a95bc",
          "sha1": "3ddda786b385a88d2f3afa1451d6c13e5b7c166a",
          "md5": "4035bb7d9ba3bdf8e9dd53bebe6cb0cb"
        }
      ]
    }
  ]
}
